//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: fileProto/bundle_Asset.proto
// Note: requires additional types generated from: fileProto/NameKey.proto
namespace ProtoDefinite
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bundle_Asset")]
  public partial class bundle_Asset : global::ProtoBuf.IExtensible
  {
    public bundle_Asset() {}
    
    private readonly global::System.Collections.Generic.List<NameKey> _namekeys = new global::System.Collections.Generic.List<NameKey>();
    [global::ProtoBuf.ProtoMember(1, Name=@"namekeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NameKey> namekeys
    {
      get { return _namekeys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}